file= "C:/Users/win10/Documents/CodigoASCII.txt"
archivo = open(file,'w')

texto = """		simbolo
codigo ascii	0	NULL	( carácter nulo )
codigo ascii	1	SOH	( inicio encabezado )
codigo ascii	2	STX	( inicio texto )
codigo ascii	3	ETX	( fin de texto )
codigo ascii	4	EOT	( fin transmisión )
codigo ascii	5	ENQ	( enquiry )
codigo ascii	6	ACK	( acknowledgement )
codigo ascii	7	BEL	( timbre )
codigo ascii	8	BS	( back space o retroceso )
codigo ascii	9	HT	( tabulador horizontal )
codigo ascii	10	LF	( salto de linea )
codigo ascii	11	VT	( tabulador vertical )
codigo ascii	12	FF	( form feed )
codigo ascii	13	CR	( retorno de carro )
codigo ascii	14	SO	( shift Out )
codigo ascii	15	SI	( shift In )
codigo ascii	16	DLE	( data link escape )
codigo ascii	17	DC1	( device control 1 )
codigo ascii	18	DC2	( device control 2 )
codigo ascii	19	DC3	( device control 3 )
codigo ascii	20	DC4	( device control 4 )
codigo ascii	21	NAK	( negative acknowledgement )
codigo ascii	22	SYN	( synchronous idle )
codigo ascii	23	ETB	( end of trans. block )
codigo ascii	24	CAN	( cancel )
codigo ascii	25	EM	( end of medium )
codigo ascii	26	SUB	( substitute )
codigo ascii	27	ESC	( escape )
codigo ascii	28	FS	( file separator )
codigo ascii	29	GS	( group separator )
codigo ascii	30	RS	( record separator )
codigo ascii	31	US	( unit separator )

codigo ascii	32	 	( espacio en blanco )
codigo ascii	33	!	( signo de admiracion )
codigo ascii	34	"	( comillas dobles, comillas altas o inglesas )
codigo ascii	35	#	( numeral )
codigo ascii	36	$	( signo pesos )
codigo ascii	37	%	( signo de porcentaje, por ciento )
codigo ascii	38	&	( Y, ampersand, et latina )
codigo ascii	39	'	( comillas simples, apóstrofe )
codigo ascii	40	(	( abre parentesis )
codigo ascii	41	)	( cierra parentesis )
codigo ascii	42	*	( asterisco )
codigo ascii	43	+	( signo mas, suma, positivo )
codigo ascii	44	,	( coma )
codigo ascii	45	-	( signo menos, resta, negativo, guión medio )
codigo ascii	46	.	( punto )
codigo ascii	47	/	( barra inclinada, división, operador aritmético de cociente )
codigo ascii	48	0	( número cero )
codigo ascii	49	1	( número uno )
codigo ascii	50	2	( número dos )
codigo ascii	51	3	( número tres )
codigo ascii	52	4	( número cuatro )
codigo ascii	53	5	( número cinco )
codigo ascii	54	6	( número seis )
codigo ascii	55	7	( número siete )
codigo ascii	56	8	( número ocho )
codigo ascii	57	9	( número nueve )
codigo ascii	58	:	( dos puntos )
codigo ascii	59	;	( punto y coma )
codigo ascii	60	<	( mayor que )
codigo ascii	61	=	( Signo igual, igualdad, igual que )
codigo ascii	62	>	( menos que )
codigo ascii	63	?	( cierra signo interrogacion )
codigo ascii	64	@	( arroba )
codigo ascii	65	A	( letra A mayuscula )
codigo ascii	66	B	( letra B mayuscula )
codigo ascii	67	C	( letra C mayuscula )
codigo ascii	68	D	( letra D mayuscula )
codigo ascii	69	E	( letra E mayuscula )
codigo ascii	70	F	( letra F mayuscula )
codigo ascii	71	G	( letra G mayuscula )
codigo ascii	72	H	( letra H mayuscula )
codigo ascii	73	I	( letra I mayuscula )
codigo ascii	74	J	( letra J mayuscula )
codigo ascii	75	K	( letra K mayuscula )
codigo ascii	76	L	( letra L mayuscula )
codigo ascii	77	M	( letra M mayuscula )
codigo ascii	78	N	( letra N mayuscula )
codigo ascii	79	O	( letra O mayuscula )
codigo ascii	80	P	( letra P mayuscula )
codigo ascii	81	Q	( letra Q mayuscula )
codigo ascii	82	R	( letra R mayuscula )
codigo ascii	83	S	( letra S mayuscula )
codigo ascii	84	T	( letra T mayuscula )
codigo ascii	85	U	( letra U mayuscula )
codigo ascii	86	V	( letra V mayuscula )
codigo ascii	87	W	( letra W mayuscula )
codigo ascii	88	X	( letra X mayuscula )
codigo ascii	89	Y	( letra Y mayuscula )
codigo ascii	90	Z	( letra Z mayuscula )
codigo ascii	91	[	( abre corchetes )
codigo ascii	92	\	( barra invertida, contrabarra, barra inversa )
codigo ascii	93	]	( cierra corchetes )
codigo ascii	94	^	( intercalación, acento circunflejo )
codigo ascii	95	_	( guión bajo, subrayado, subguión )
codigo ascii	96	`	( acento grave )
codigo ascii	97	a	( letra a minuscula )
codigo ascii	98	b	( letra b minuscula )
codigo ascii	99	c	( letra c minuscula )
codigo ascii	100	d	( letra d minuscula )
codigo ascii	101	e	( letra e minuscula )
codigo ascii	102	f	( letra f minuscula )
codigo ascii	103	g	( letra g minuscula )
codigo ascii	104	h	( letra h minuscula )
codigo ascii	105	i	( letra i minuscula )
codigo ascii	106	j	( letra j minuscula )
codigo ascii	107	k	( letra k minuscula )
codigo ascii	108	l	( letra l minuscula )
codigo ascii	109	m	( letra m minuscula )
codigo ascii	110	n	( letra n minuscula )
codigo ascii	111	o	( letra o minuscula )
codigo ascii	112	p	( letra p minuscula )
codigo ascii	113	q	( letra q minuscula )
codigo ascii	114	r	( letra r minuscula )
codigo ascii	115	s	( letra s minuscula )
codigo ascii	116	t	( letra t minuscula )
codigo ascii	117	u	( letra u minuscula )
codigo ascii	118	v	( letra v minuscula )
codigo ascii	119	w	( letra w minuscula )
codigo ascii	120	x	( letra x minuscula )
codigo ascii	121	y	( letra y minuscula )
codigo ascii	122	z	( letra z minuscula )
codigo ascii	123	{	( abre llave curva, llaves curvas )
codigo ascii	124	|	( barra vertical, pleca , linea vertical )
codigo ascii	125	}	( cierra llave, llaves curvas )
codigo ascii	126	~	( signo de equivalencia, tilde, virgulilla de la ñ )
codigo ascii	127	DEL	( Suprimir, borrar, eliminar )
codigo ascii	255	nbsp	espacio sin separación - non breaking space  """

archivo.write(texto)
archivo.close()

